# Generated by Django 4.0.2 on 2022-04-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=11, null=True)),
                ('reps', models.IntegerField(default=100, max_length=5)),
                ('tot_cal', models.IntegerField(default=100, max_length=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('workout_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=11, null=True)),
                ('weight', models.CharField(max_length=11, null=True)),
                ('bmi', models.CharField(max_length=11, null=True)),
                ('body_type', models.CharField(max_length=11, null=True)),
                ('pro_user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=11, null=True)),
                ('food_quant', models.IntegerField(default=100, max_length=5)),
                ('calories', models.CharField(max_length=11, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('food_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
