# Generated by Django 4.0.2 on 2022-05-07 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_workout_profile_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='achived',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='workout',
            name='goal',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='workout',
            name='msic_type',
            field=models.CharField(default='rock', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_quant',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='workout',
            name='tot_cal',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.CreateModel(
            name='daily_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spo2', models.IntegerField(blank=True, default=5)),
                ('heart_rate', models.IntegerField(blank=True, default=5)),
                ('sleep', models.IntegerField(blank=True, default=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('daily_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
