# Generated by Django 4.0.2 on 2022-05-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, null=True)),
                ('email', models.CharField(max_length=11, null=True)),
                ('message', models.CharField(max_length=11, null=True)),
            ],
        ),
    ]
