# Generated by Django 4.0.2 on 2022-05-07 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
